"feature: server":
  - all:
      - or:
          head-branch: ['^feature', '^feat']
          title: ['(feature|feat)(\s*[-:_]\s*.+)?', '(feature|feat):.*']
          body: ['(feature|feat)(\s*[-:_]\s*.+)?', '(feature|feat):.*']
      - changed-files: ['src/**/*']

"feature: client":
  - all:
      - or:
          head-branch: ['^feature', '^feat']
          title: ['(feature|feat)(\s*[-:_]\s*.+)?', '(feature|feat):.*']
          body: ['(feature|feat)(\s*[-:_]\s*.+)?', '(feature|feat):.*']
      - changed-files: ['client/**/*']

"feature: common":
  - all:
      - or:
          head-branch: ['^feature', '^feat']
          title: ['(feature|feat)(\s*[-:_]\s*.+)?', '(feature|feat):.*']
          body: ['(feature|feat)(\s*[-:_]\s*.+)?', '(feature|feat):.*']
      - changed-files: ['common/**/*']

"feature: macros":
  - all:
      - or:
          head-branch: ['^feature', '^feat']
          title: ['(feature|feat)(\s*[-:_]\s*.+)?', '(feature|feat):.*']
          body: ['(feature|feat)(\s*[-:_]\s*.+)?', '(feature|feat):.*']
      - changed-files: ['macros/**/*']

"bugfix: server":
  - all:
      - or:
          head-branch: ['^fix', '^bugfix']
          title: ['(fix|bugfix)(\s*[-:_]\s*.+)?', '(fix|bugfix):.*']
          body: ['(fix|bugfix)(\s*[-:_]\s*.+)?', '(fix|bugfix):.*']
      - changed-files: ['src/**/*']

"bugfix: client":
  - all:
      - or:
          head-branch: ['^fix', '^bugfix']
          title: ['(fix|bugfix)(\s*[-:_]\s*.+)?', '(fix|bugfix):.*']
          body: ['(fix|bugfix)(\s*[-:_]\s*.+)?', '(fix|bugfix):.*']
      - changed-files: ['client/**/*']

"bugfix: common":
  - all:
      - or:
          head-branch: ['^fix', '^bugfix']
          title: ['(fix|bugfix)(\s*[-:_]\s*.+)?', '(fix|bugfix):.*']
          body: ['(fix|bugfix)(\s*[-:_]\s*.+)?', '(fix|bugfix):.*']
      - changed-files: ['common/**/*']

"bugfix: macros":
  - all:
      - or:
          head-branch: ['^fix', '^bugfix']
          title: ['(fix|bugfix)(\s*[-:_]\s*.+)?', '(fix|bugfix):.*']
          body: ['(fix|bugfix)(\s*[-:_]\s*.+)?', '(fix|bugfix):.*']
      - changed-files: ['macros/**/*']

"refactor: server":
  - all:
      - or:
          head-branch: ['^refactor']
          title: ['refactor(\s*[-:_]\s*.+)?', 'refactor:.*']
          body: ['refactor(\s*[-:_]\s*.+)?', 'refactor:.*']
      - changed-files: ['src/**/*']

"refactor: client":
  - all:
      - or:
          head-branch: ['^refactor']
          title: ['refactor(\s*[-:_]\s*.+)?', 'refactor:.*']
          body: ['refactor(\s*[-:_]\s*.+)?', 'refactor:.*']
      - changed-files: ['client/**/*']

"refactor: common":
  - all:
      - or:
          head-branch: ['^refactor']
          title: ['refactor(\s*[-:_]\s*.+)?', 'refactor:.*']
          body: ['refactor(\s*[-:_]\s*.+)?', 'refactor:.*']
      - changed-files: ['common/**/*']

"refactor: macros":
  - all:
      - or:
          head-branch: ['^refactor']
          title: ['refactor(\s*[-:_]\s*.+)?', 'refactor:.*']
          body: ['refactor(\s*[-:_]\s*.+)?', 'refactor:.*']
      - changed-files: ['macros/**/*']

"documentation":
  - any:
      - or:
          head-branch: ['^docs?', '^documentation']
          title: ['(docs?|documentation)(\s*[-:_]\s*.+)?', '(docs?|documentation):.*']
          body: ['(docs?|documentation)(\s*[-:_]\s*.+)?', '(docs?|documentation):.*']
      - changed-files: ['docs/**/*', '**/*.md', '**/doc/**/*']

"cicd":
  - any:
      - or:
          head-branch: ['^ci', '^cd', '^cicd']
          title: ['(ci|cd|cicd)(\s*[-:_]\s*.+)?', '(ci|cd|cicd):.*']
          body: ['(ci|cd|cicd)(\s*[-:_]\s*.+)?', '(ci|cd|cicd):.*']
      - changed-files: ['.github/workflows/**/*'] 

"chore":
  - any:
      - or:
          head-branch: ['^chore']
          title: ['chore(\s*[-:_]\s*.+)?', 'chore:.*']
          body: ['chore(\s*[-:_]\s*.+)?', 'chore:.*']
      - changed-files: 
        - '.github/**/*'          
        - '.gitignore'          
        - '.editorconfig'       
        - 'scripts/**/*'          
        - '**/Cargo.toml'       
        - '**/Cargo.lock'       
        - '**/*.yml'
