pub const HEADER_AFTER_SECTION_LENGTH_SIZE: u8 = 9;

pub const HEADER_SIZE: u8 = 3;

pub const PCR_PID_UPPER_MASK: u8 = 0x1F;

pub const PCR_PID_LOWER_MASK: u8 = 0xFF;

pub const PROGRAM_INFO_LENGTH_UPPER_MASK: u8 = 0x0F;

pub const PROGRAM_INFO_LENGTH_LOWER_MASK: u8 = 0xFF;

pub const MAX_PROGRAM_INFO_LENGTH: u16 = 0x03FF;

pub const ELEMENTARY_PID_UPPER_MASK: u8 = 0x1F;

pub const ELEMENTARY_PID_LOWER_MASK: u8 = 0xFF;

pub const ES_INFO_LENGTH_UPPER_MASK: u8 = 0x0F;
pub const ES_INFO_LENGTH_LOWER_MASK: u8 = 0xFF;

pub const STREAM_LENGTH: u16 = 5;
