
name: PR Assignment

on:
  pull_request:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      repository-projects: write

    steps:
      - name: Assign PR to opener
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: [context.payload.pull_request.user.login]
            });

      - name: Add to Netpix project
        uses: actions/github-script@v6
        with:
          script: |
            const query = `mutation($projectId: ID!, $prId: ID!) {
              addProjectV2ItemById(input: {projectId: $projectId, contentId: $prId}) {
                item {
                  id
                }
              }
            }`;
            
            const projectId = '4';
            const prId = context.payload.pull_request.node_id;
            
            await github.graphql(query, {
              projectId: projectId,
              prId: prId
            });