name: Clippy Check

on:
  pull_request:
    types: [ opened, synchronize ]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  clippy:
    name: Clippy Analysis
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [client, common]
        include:
          - package: client
            path: ./client
          - package: common
            path: ./common
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      
      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Install libpcap
        run: sudo apt-get install libpcap-dev
      
      - name: Run Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --manifest-path ${{ matrix.path }}/Cargo.toml --all-features --all-targets -- -D warnings
          name: Clippy ${{ matrix.package }}
