name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - '**'

permissions:
  contents: read
  pull-requests: write

jobs:
  test-common:
    name: Test Common Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2024-02-04
      - name: Install libpcap
        run: sudo apt-get install libpcap-dev
      
      - name: Run tests
        working-directory: ./common
        run: cargo test
      
      - name: Report failure
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ Common package tests failed. Please check the CI run for details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
            })