pub const MAX_SECTION_LENGTH: u16 = 0x3FD;
pub const SECTION_SYNTAX_INDICATOR_MASK: u8 = 0x80;
pub const SECTION_LENGTH_UPPER_MASK: u8 = 0x0F;
pub const VERSION_NUMBER_MASK: u8 = 0x3E;
pub const CURRENT_NEXT_INDICATOR_MASK: u8 = 0x01;
